indent_type = "Spaces"
indent_width = 2
column_width = 120
syntax = "All"
line_endings = "Unix"
quote_style = "AutoPreferDouble"
call_parentheses = "Always"
block_newline_gaps = "Never"

[sort_requires]
enabled = true
